In [61]:
import pandas as pd
import numpy as np
df = pd.read_csv("hf://datasets/Rubigha/alfarisbachmid_dirty-financial-transactions-dataset/dirty_financial_transactions.csv")
df

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
1,T0002,2020-02-10,C3156,Coffee,469.0,-445.34202525395585,creditcard,Pending
2,T0003,2025-02-30,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tab,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2025-02-30,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed
...,...,...,...,...,...,...,...,...
99995,NaN,2021-10-06,C1743,Headphones,-8.0,240.0032380562687,PayPal,complete
99996,T99997,2024-08-25,C4830,Smartphone,NaN,503.82951729633896,credit card,Completed
99997,T99998,2023-13-01,C280,Laptop,-10.0,NaN,PayPal,completed
99998,T99999,2020-07-12,C4059,Headphones,10.0,NaN,PayPal,Completed
99999,T100000,2023-10-04,C1805,Tablet,2.0,89.37402345793535,PayPal,Failed

In [62]:
df.shape

(100000, 8)

In [63]:
df.describe()

           Quantity
count  94981.000000
mean     183.883914
std      299.292365
min      -10.000000
25%       -3.000000
50%        6.000000
75%      327.000000
max     1000.000000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      94982 non-null   object
 1   Transaction_Date    95120 non-null   object
 2   Customer_ID         95122 non-null   object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: float64(1), object(7)
memory usage: 6.1+ MB

In [65]:

df.isna().sum()

Transaction_ID         5018
Transaction_Date       4880
Customer_ID            4878
Product_Name              0
Quantity               5019
Price                 33497
Payment_Method            0
Transaction_Status    16679
dtype: int64

In [66]:
df.nunique()

Transaction_ID        94040
Transaction_Date       1861
Customer_ID            5000
Product_Name             46
Quantity                921
Price                 65757
Payment_Method            7
Transaction_Status        5
dtype: int64

In [67]:
df[df.duplicated(keep=False)]

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
26,T73466,2025-02-30,C2702,Coffee Machine,-5.0,555.6133483579025,creditcard,complete
141,T77766,2023-13-01,C4226,Tablet,-7.0,$862.48,Credit Card,complete
161,T17515,2024-11-25,C3287,Smartphone,-9.0,850.4985899006939,Credit Card,Pending
323,T22566,NaN,C530,Smartphone,365.0,$103.82,PayPal,complete
359,T66876,2023-13-01,C4712,Headphones,-5.0,776.5305169596752,PayPal,NaN
...,...,...,...,...,...,...,...,...
99674,T47093,2023-13-01,C4823,Tablet,-6.0,-522.4003199263182,creditcard,Completed
99786,T15545,2023-13-01,C2823,Laptop,3.0,NaN,pay pal,completed
99866,T6571,2023-13-01,C4483,Smartphone,2.0,421.99494928905284,PayPal,completed
99984,NaN,2022-01-26,C4753,Laptop,480.0,-558.7481358840021,Cash,completed
99999,T100000,2023-10-04,C1805,Tablet,2.0,89.37402345793535,PayPal,Failed

In [68]:
df=df.drop_duplicates()

In [69]:
df.shape

(99006, 8)

In [70]:
((df["Transaction_ID"].isna().sum())*100)/(len(df))

np.float64(5.015857624790416)

In [71]:
df = df.dropna(subset=["Transaction_ID"])

In [72]:
df[df["Transaction_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Customer_ID, Product_Name, Quantity, Price, Payment_Method, Transaction_Status]
Index: []

In [73]:
df.shape

(94040, 8)

In [74]:
bad_dates = ["2023-13-01", "2025-02-30"]
bad_dates_count = df["Transaction_Date"].isin(bad_dates).sum()
print(f"Number of bad dates: {bad_dates_count}")

Number of bad dates: 59594

In [75]:
df["Transaction_Date"]=df["Transaction_Date"].replace("2023-13-01","2024-01-01")
df["Transaction_Date"]=df["Transaction_Date"].replace("2025-02-30","2025-03-01")

In [76]:
bad_dates_count = df["Transaction_Date"].isin(bad_dates).sum()
print(f"Number of bad dates: {bad_dates_count}")
df.shape

Number of bad dates: 0

(94040, 8)

In [77]:
df["Transaction_Date"]=pd.to_datetime(df["Transaction_Date"])
print(df["Transaction_Date"].dtype)

datetime64[ns]

In [78]:
((df["Transaction_Date"].isna().sum())*100)/(len(df))

np.float64(4.876648234793705)

In [79]:
df=df.dropna(subset=["Transaction_Date"])
df.shape

(89454, 8)

In [80]:
((df["Customer_ID"].isna().sum())*100)/(len(df))

np.float64(4.889663961365618)

In [81]:
df=df.dropna(subset=["Customer_ID"])
df.shape

(85080, 8)

In [82]:
df["Product_Name"]=df["Product_Name"].str.strip()
df["Product_Name"].value_counts()

Product_Name
Tablet            15664
Smartphone        15574
Laptop            15561
Coffee Machine    15436
Headphones        15367
Tabl                305
Lapt                305
Ta                  304
Table               303
La                  302
Lapto               291
T                   288
Tab                 281
Lap                 281
L                   268
Coffee              221
Smartph             202
H                   184
S                   183
Headp               177
He                  177
Smartphon           175
Head                175
Headpho             174
Smart               173
Smartp              173
Headphon            171
Headphone           168
Sm                  163
Headph              163
Sma                 159
Smartpho            158
Hea                 152
Smar                143
Coffee Machi        132
Coffee Ma           131
Coffee Mach         123
Coffee Machin       123
Coffee M            117
C                   117
Cof                 114
Coffe               111
Coffee Mac          102
Coff                 96
Co                   93
Name: count, dtype: int64

In [83]:
df["Product_Name"]=df["Product_Name"].replace(["Tabl","Ta","Table","T","Tab","Tablet"],"Tablet")
df["Product_Name"]=df["Product_Name"].replace(["Lapt","La","Lapto","Lap","L","Laptop"],"Laptop")
df["Product_Name"]=df["Product_Name"].replace(["Coffee","Coffee Machi","Coffee Ma","Coffee Machin","Coffee Mach","Coffee M","C","Cof","Coffe","Coffee Mac","Coff","Co","Coffee Machine"],"Coffee Machine") 
df["Product_Name"]=df["Product_Name"].replace(["Smar","Smartpho","Sma","Sm","Smart","Smartp","Smartphon","S","Smartph","Smartphone"],"Smartphone")
df["Product_Name"]=df["Product_Name"].replace(["Hea","Headph","Headphone","Headphon","Head","Headpho","He","Headp","H"],"Headphones")

In [84]:
df["Product_Name"].value_counts()

Product_Name
Tablet            17145
Smartphone        17103
Laptop            17008
Coffee Machine    16916
Headphones        16908
Name: count, dtype: int64

In [85]:
((df["Quantity"].isna().sum())*100)/(len(df))

np.float64(4.98119417019276)

In [86]:
((df["Quantity"]<0).sum()*100)/(len(df))

np.float64(31.671368124118477)

In [87]:
df['Quantity_Invalid'] = df['Quantity'] < 0
df.loc[df['Quantity'] < 0, 'Quantity'] = np.nan
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [88]:
df["Price"] = df["Price"].apply(lambda x: x.replace("$", "").strip() if isinstance(x, str) else x)
df["Price"] = pd.to_numeric(df["Price"], errors='coerce')
(df["Price"]).dtype

dtype('float64')

In [89]:
((df["Price"].isna().sum())*100)/(len(df))

np.float64(33.44969440526563)

In [90]:
((df["Price"]<0).sum()*100)/(len(df))

np.float64(33.27338975082276)

In [91]:
df['Price_Invalid'] = df['Price'] < 0
df.loc[df['Price'] < 0, 'Price'] = np.nan
df['Price'] = df.groupby('Product_Name')['Price'].transform(
    lambda x: x.fillna(x.median())
)
df['Price'] = df['Price'].fillna(df['Price'].median())

In [92]:
((df["Payment_Method"].isna().sum())*100)/(len(df))

np.float64(0.0)

In [93]:
df["Payment_Method"]=df["Payment_Method"].str.strip()
df["Payment_Method"].value_counts()

Payment_Method
PayPal         24083
Credit Card    12299
pay pal        12245
creditcard     12222
credit card    12126
Cash           12105
Name: count, dtype: int64

In [94]:
df["Payment_Method"]=df["Payment_Method"].replace(["Credit Card","creditcard","credit card"],"Credit Card")
df["Payment_Method"]=df["Payment_Method"].replace(["pay pal","PayPal","PayPal"],"Pay Pal")

In [95]:
((df["Transaction_Status"].isna().sum())*100)/(len(df))

np.float64(16.643159379407617)

In [96]:
df["Transaction_Status"]=df["Transaction_Status"].str.strip()
df['Status_Missing'] = df['Transaction_Status'].isna()
df["Transaction_Status"]=df["Transaction_Status"].replace(np.nan,"Unknown")
df["Transaction_Status"].value_counts()

Transaction_Status
Failed       14251
complete     14250
completed    14201
Pending      14198
Unknown      14160
Completed    14020
Name: count, dtype: int64

In [97]:
df["Transaction_Status"]=df["Transaction_Status"].replace(["complete","completed","Completed"],"Completed")

In [98]:
df

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status,Quantity_Invalid,Price_Invalid,Status_Missing
0,T0001,2024-08-02,C2205,Headphones,106.0,420.210000,Pay Pal,Unknown,True,False,True
1,T0002,2020-02-10,C3156,Coffee Machine,469.0,527.639314,Credit Card,Pending,False,True,False
2,T0003,2025-03-01,C2919,Tablet,106.0,810.993012,Credit Card,Completed,True,False,False
3,T0004,2020-08-17,C3009,Tablet,106.0,868.608341,Pay Pal,Pending,True,False,False
4,T0005,2025-03-01,C3488,Coffee Machine,106.0,527.639314,Pay Pal,Completed,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...
99993,T99994,2024-11-24,C3391,Tablet,911.0,519.494178,Cash,Pending,False,True,False
99994,T99995,2025-03-01,C2153,Smartphone,741.0,518.152424,Pay Pal,Completed,False,False,False
99996,T99997,2024-08-25,C4830,Smartphone,106.0,503.829517,Credit Card,Completed,False,False,False
99997,T99998,2024-01-01,C280,Laptop,106.0,525.461554,Pay Pal,Completed,True,False,False
99998,T99999,2020-07-12,C4059,Headphones,10.0,525.092723,Pay Pal,Completed,False,False,False

In [99]:
df.columns

Index(['Transaction_ID', 'Transaction_Date', 'Customer_ID', 'Product_Name',
       'Quantity', 'Price', 'Payment_Method', 'Transaction_Status',
       'Quantity_Invalid', 'Price_Invalid', 'Status_Missing'],
      dtype='object')

In [100]:
final_df=df[['Transaction_ID','Transaction_Date','Customer_ID','Product_Name','Quantity','Price','Payment_Method','Transaction_Status']]

In [102]:
final_df.to_csv("cleaned_financial_transaction.csv", index=False)